- name: Setup Jenkins
  ansible.builtin.include_tasks:
    file: setup_jenkins.yml
  when: setup_jenkins | bool

- name: Setup Tools
  ansible.builtin.include_tasks:
    file: setup_tools.yml
  when: setup_tools | bool


