name: Run Vault Setup
on: [workflow_dispatch]
jobs:
  Provision:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run Vault Setup
        run: ansible-playbook -i vault-internal.rdevopsb80.online, tool-setup.yml -e ansible_user=ec2-user -e ansible_password=DevOps321 -e tool_name=vault

